### ISSUE TITLE
Fix code coverage report

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/light-date#3]
Coveralls shows about 93% coverage, but it should be 100% - missing lines don't make any sense ([example](https://coveralls.io/builds/32966774/source?filename=src/index.ts)).

**Comment by hildjj** [comment]
Looks like that only happens with node 10, I was able to re-create with:

```
nvm install 10
nvm use 10
npm i
npm run test
```

The actual tests work just fine; I bet this is an issue with source mapping.

**Comment by xxczaki** [comment]
Fixed.
